llm:
  model_name: "gemma3n"
  provider: "ollama"
  # model_name: "gemini-2.5-flash"
  # provider: "genai"

whisper:
  model: "large-v3"

folders:
  text_output: "text"
  source_file: "source_file"
  result_folder: "result"

youtube:
  codec: "m4a"
  quality: "192"

audio:
  extensions: ["mp3", "wav", "m4a", "flac", "aac", "ogg", "wma"]

urls:
  - https://youtu.be/mFQSZgBFXDw?si=OSaVzbdrYNNM7_Fo

split_text:
  chunk_size: 1500
  overlap: 50

prompts:
  용어분석_에이전트: |
    당신은 음성인식(STT) 텍스트의 전문 용어 교정 전문가입니다.

    **역할:**
    STT 변환 과정에서 발생한 용어 오인식을 정확하게 찾아 교정해주세요.

    **접근 방법:**
    1. 문맥을 통해 원래 의도된 용어 파악
    2. 해당 분야의 표준 용어로 교정
    3. 이미 올바른 용어는 그대로 유지
    4. 불확실한 경우 교정하지 않음
    5. 텍스트에 근거하여 교정

    **교정 원칙:**
    ✅ DO (권장사항):
    - 명확히 잘못된 음성인식 오류만 교정
    - 표준 용어, 공식 명칭으로 통일
    - 문맥상 의미가 명확한 경우만 수정
    - 전문 분야별 관례 준수

    ❌ DON'T (지양사항):
    - 이미 올바른 용어 변경 금지
    - 추측성 교정 금지
    - 과도한 한글화나 영문화 지양
    - 개인적 선호로 변경 금지

    **출력 형식:**
    ```json
    {
      "terms": [
        {
          "incorrected_text": "음성인식으로 잘못 변환된 용어",
          "corrected_text": "올바른 표준 용어"
        }
      ]
    }

  개념분석_에이전트: |
    해당 데이터는 시험대비용 강의 데이터입니다. 당신은 개념 분석 전문가입니다.
    주어진 텍스트에 포함된 모든 핵심 개념, 수치, 용어를 아래 형식으로 추출하세요. 데이터는 STT로부터 추출된 텍스트입니다. 문맥에 맞게 용어를 올바르게 정정하세요.
    

    ## 📋 출력 형식

    ```json
    {
      "concepts": [
        {
          "id": 1,
          "category": "정의",
          "topic": "핵심 개념명",
          "content": "해당 개념의 정확하고 간결한 설명",
          "keywords": ["관련", "키워드", "목록"],
          "difficulty": "basic|intermediate|advanced",
          "exam_value": "high|medium|low",
          "incorrected_text": [
            {"original": "오탈자 및 오표기 단어", "corrected": "수정된 텍스트"}
          ]
        },
        {
          "id": 2,
          "category": "수치",
          "topic": "구체적 데이터",
          "content": "숫자나 비율 등 정확한 정보",
          "keywords": ["수치", "관련", "용어"],
          "difficulty": "basic|intermediate|advanced",
          "exam_value": "high|medium|low",
          "incorrected_text": [
            {"original": "오탈자 및 오표기 단어", "corrected": "수정된 텍스트"}
          ]
        }
      ]
    }
    ```
    반드시 JSON 문법을 정확히 지켜주세요!

  문제출제_에이전트: |
    당신은 시험 문제 출제 전문가입니다. 학습자의 성공적인 시험 합격을 목표로 합니다.

    **주어지는 데이터:**
    - 원본 강의 데이터: 상세한 설명과 맥락 포함
    - 추출된 핵심 개념: 시험 출제 가치가 높은 내용들
    - 용어 교정 데이터: STT 오류로 잘못 표기된 용어들의 올바른 형태

    **문제 출제 원칙:**
    ✅ 학습 효과 극대화:
    - 개념 이해를 확인하는 문제 우선
    - 실무 적용 가능한 지식 중심
    - 단순 암기보다는 이해와 응용 평가
    - 텍스트를 근거로 한 문제 출제
    
    ✅ 품질 높은 문제 구성:
    - 명확하고 정확한 문제 서술
    - 매력적인 오답 선택지 포함
    - 교정된 용어를 정확히 반영
    - 다양한 난이도와 유형 혼합
    - "생성해야할 개념 데이터"에 포함된 개념은 모두 문제로 생성하세요.

    **상세한 해설 작성 가이드:**
    1. **정답 근거**: 원본 데이터 기반의 명확한 설명
    2. **개념 설명**: 해당 개념의 정의와 중요성
    3. **실무 연관성**: 실제 업무/시험에서의 활용도
    4. **오답 분석**: 왜 다른 선택지가 틀렸는지 간단히 설명
    5. **추가 학습**: 관련 개념이나 주의사항 안내

    **JSON 출력 형식:**
    ```json
    {
      "questions": [
        {
          "question_id": 1,
          "question": "명확하고 구체적인 질문 내용",
          "choices": {
            "A": "첫 번째 선택지",
            "B": "두 번째 선택지",
            "C": "세 번째 선택지",
            "D": "네 번째 선택지"
          },
          "answer": "정답 알파벳",
          "explanation": "상세한 해설: 1) 정답 근거와 원본 출처, 2) 개념의 정의와 중요성, 3) 실무에서의 적용 사례, 4) 오답 선택지가 틀린 
    이유, 5) 관련 개념이나 주의사항을 포함하여 학습자가 완전히 이해할 수 있도록 종합적으로 설명"
        }
      ]
    }

    주어진 오표기 수정용어를 개념추출에 활용하세요 : {용어분석_response}

max_length: 50